accounts/urls.py
from django.urls import path
from accounts import views
#from django.contrib.auth.views import (password_reset, password_reset_done,
 #      
 #                                  password_reset_confirm, password_reset_complete)




#Template Tagging
app_name = 'accounts'

urlpatterns = [

    # path('login/', views.user_login,  name='user_login'),
    # path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.StudentSignUpView.as_view(), name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/siwes/', views.edit_details, name='edit_details'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    # path('change-password/', views.change_password, name='change_password'),

    #path('reset-password/', password_reset,{'template_name':
    #'accounts/reset_password.html', 'post_reset_redirect':
    #'accounts:password_reset_done', 'email_template_name':
    #'accounts/reset_password_email.html'}, name='reset_password'),


    #path('reset_password-password/done/',  password_reset_done, {'template_name':
    #'accounts/reset_done.html'}, name='password_reset_done'),

    #path('reset_password-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',  password_reset_confirm, {'template_name':
    #'accounts/reset_confirm.html', 'post_reset_redirect':
    #'accounts:password_reset_complete'}, name='password_reset_confirm'),


    #path('reset-password/complete/',  password_reset_complete, {'template_name':
    #'accounts/reset_complete.html'}, name='password_reset_complete'),

]

fupreproject/urls.py
from django.contrib import admin
from django.urls import include, path
from accounts import views
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('contact/', views.ContactPage, name='contact'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

            # Autenticate 3rd party
    path('profile/login/', auth_views.LoginView.as_view(), name='login'),
    path('profile/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('profile/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
# accounts.forms.py
import re
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserCreationForm


from accounts.models import SiwesInformation

User = get_user_model()



Session = (
    ('', 'Select Year'),
    ('2020/2021', '2020/2021'),
)

college = (
    ('', 'Select College'),
    ('COLLEGE OF SCIENCE', 'Science'),
    ('COLLEGE OF TECHNOLOGY', 'Technology')
)

Level = (
    ('', 'Select Level'),
    ('300', '300'),
    ('400','400')
)

Department = (
    ('', 'Select Dept'),
    ('Chemistry', 'Chemistry'),
    ('Industrial Chemistry', 'Industrial Chemistry'),
    ('Physics', 'Physics'),
    ('Geophysics', 'Geophysics'),
    ('Geology', 'Geology'),
    ('Computer Science', 'Computer Science'),
    ('Mathematics', 'Mathematics'),
    ('Environmental Management Toxicology', 'Environmental Sci'),
    ('Petroleum Engineering', 'Petroleum Engr'),
    ('Chemical Engineering','Chemical Engr'),
    ('Electrical Electronics Engineering', 'Elect/Elect Engr'),
    ('Mechanical Engineering', 'Mechanical Engr'),
    ('Marine Engineering', 'Marine Engr')
)

sdept = ('Chemistry', 'Industrial Chemistry', 'Physics', 'Geophysics', 'Geology', 'Computer Science', 'Mathematics', 'Environmental Management Toxicology')
tdept = ('Petroleum Engineering', 'Chemical Engineering', 'Electrical Electronics Engineering', 'Mechanical Engineering', 'Marine Engineering')

class RegisterForm(UserCreationForm):
    # password1 = forms.CharField(widget=forms.PasswordInput)
    # password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('matric_number',  'full_name', 'email', 'session', 'College', 'department', 'level', 'image')

    # def clean_matric_number(self):
    #     a = self.cleaned_data.get('matric_number')
    #     matric_number = a.upper()
    #     qs = User.objects.filter(matric_number=matric_number)
    #     if qs.exists():
    #         raise forms.ValidationError("Matriculation Number Already Taken")
    #     # else:
    #     #     if not re.search("^COS/.*\\d{4}.*/2016$", matric_number) or re.search("^COS/.*\\d{4}.*/2017$", matric_number) or re.search("^COT/.*\\d{4}.*/2015$", matric_number) or re.search("^COT/.*\\d{4}.*/2016$", matric_number):
    #     #         raise forms.ValidationError("Invalid Matriculation Number")
    #     return matric_number

    # def clean_email(self):
    #     email = self.cleaned_data.get('email')
    #     qs = User.objects.filter(email=email)
    #     if qs.exists():
    #         raise forms.ValidationError("email is taken")
    #     return email

    # def clean_level(self):
    #     College = self.cleaned_data.get('College')
    #     level   = self.cleaned_data.get('level')
    #     if not re.search("^CO.*CE$", College) and level == '300':
    #         raise forms.ValidationError("Recheck College and Level Fields")
    #     else:
    #         if not re.search("^CO.*GY$", College) and level == '400':
    #             raise forms.ValidationError("Recheck College and Level Fields")
    #     return level

    # def clean_department(self):
    #     College     = self.cleaned_data.get('College')
    #     department  = self.cleaned_data.get('department')
    #     if not re.search("^CO.*CE$", College) and department in sdept:
    #         raise forms.ValidationError("Recheck College and Department Fields")
    #     else:
    #         if not re.search("^CO.*GY$", College) and department in tdept:
    #             raise forms.ValidationError("Recheck College and Department Fields")
    #     return department

    # def clean_password2(self):
    #     # Check that the two password entries match
    #     password1 = self.cleaned_data.get("password1")
    #     password2 = self.cleaned_data.get("password2")
    #     if password1 and password2 and password1 != password2:
    #         raise forms.ValidationError("Passwords don't match")
    #     return password2


    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        # user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'email', 'full_name', 'matric_number',
            'session', 'email', 'College',
             'department', 'level',
             )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class EditProfileForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = (
            'matric_number',  'full_name', 'email',
            'session', 'College', 'department',
            'level','password'
            )

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = (
            'matric_number',  'full_name', 'email',
             'session', 'College', 'department',
             'level','password', 'is_active', 'admin'
             )

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class EditSiwesForm(forms.ModelForm):
    """A form for updating siwes information. Includes all the fields on
    the SiwesInformation model.
    """

    class Meta:
        model = SiwesInformation
        fields = (
            'bankName', 'accountNo', 'phoneNo',
            'industryName', 'industryAddress',
             'industrySupervisorname',
             'industrySupervisorPhoneno'
             )

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from accounts.forms import RegisterForm, EditSiwesForm, EditProfileForm, User
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from django.views.generic import CreateView, ListView, UpdateView

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('accounts:user_login'))

    else:
        form = RegisterForm()

    args = {'form': form}
    return render(request, 'registration/signup.html', args)



class StudentSignUpView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('login')

@login_required
def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)


        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
        else:
            return redirect('/accounts/profile/edit')
    else:
        form = EditProfileForm(instance=request.user)

    args = {'form': form}
    return render(request, 'accounts/edit_profile.html', args)


@login_required
def edit_details(request):
    if request.method == 'POST':
        form = EditSiwesForm(request.POST, request.FILES, instance=request.user.siwesinformation)


        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
        else:
            return redirect('/accounts/profile/siwes')
    else:
        form = EditSiwesForm(instance=request.user.siwesinformation)

    args = {'form': form}
    return render(request, 'accounts/edit_siwes.html', args)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/accounts/profile')
        else:
            return redirect('/accounts/change-password')
    else:
        form = PasswordChangeForm(user=request.user)

    for field in form.fields.values():
        field.help_text = None

    args = {'form': form}
    return render(request, 'accounts/change_password.html', args)


templates/accounts/change_password.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>Changepwd</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
  </head>
  <body>

      <br>

      <!-- Header -->
      <header id="header" class="">
        <div class="container">

          <div class="navbar-header">
            <!-- Logo -->
            <div class="navbar-brand">
              <a class="logo" href="{% url 'accounts:view_profile' %}">
                <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
              </a>
            </div>
            <!-- /Logo -->

            <!-- Mobile toggle -->
            <button class="navbar-toggle">
              <span></span>
            </button>
            <!-- /Mobile toggle -->
          </div>


          <!-- Navigation -->
          <nav id="nav">
            <ul class="main-menu nav navbar-nav navbar-right">
              <li><a style="color:black;"href="{% url 'accounts:view_profile' %}">Dashboard</a></li>
              <!-- <li><a href="/accounts/profile/edit">Edit Profile</a></li> -->
              <li><a style="color:black;" href="{% url 'accounts:edit_details' %}">Siwes Info</a></li>
              <li><a style="color:black;" href="{% url 'accounts:change_password' %}">Change Password</a></li>
              <li><a style="color:black;" href="{% url 'accounts:user_logout' %}">Log out</a></li>
            </ul>
          </nav>
          <!-- /Navigation -->

      </div>
      </header>
      <!-- /Header -->

        <br><br><br>
        <br><br><br>
        <br><br><br>
        <div class="" style="color:black;">
          <form class=""  method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-md-4 mb-0">

              </div>
              <div class="form-group col-md-4 mb-0">
                  <p>{{ form|crispy }}</p>
              </div>
              <div class="form-group col-md-4 mb-0">

              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-7 mb-0">

              </div>
            <div class="form-group col-md-5 mb-0">
              <input type="submit" name="" value="submit" class="btn btn-success">
            </div>
            <div class="form-group col-md-0 mb-0">

            </div>
          </div>
        </form>
      </div>
      <br><br>

      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <p style="color:black;"><strong> © 2020. Ogbe Larry Inc | FUPRE SIWES </strong> </p>
          </div>
        </div>
        </div>




        <!-- preloader -->
        <div id='preloader'><div class='preloader'></div></div>
        <!-- /preloader -->

        <!-- jQuery Plugins -->
        <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/main.js" %}"></script>
  </body>
</html>

templates/accounts/edit_profile.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>This is the Authenticated edit profile Page</h1>

    <form class="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" name="" value="submit">
    </form>
  </body>
</html>

templates/accounts/edit_siwes.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>Siwes</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
    <style>
        body, html {
          height: 100%;
          font-family: Arial, Helvetica, sans-serif;
        }

        * {
          box-sizing: border-box;
        }

        .bg-img {
          /* The image used */
          background-image: url("{% static 'images/ab.jpg' %}");

          min-height: 790px;
          /* height: 100%; */

          /* Center and scale the image nicely */
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
          position: relative;
          opacity:0.8;
        }

    </style>
  </head>
  <body>


      <br>

      <!-- Header -->
      <header id="header" class="">
        <div class="container">

          <div class="navbar-header">
            <!-- Logo -->
            <div class="navbar-brand">
              <a class="logo" href="{% url 'accounts:view_profile' %}">
                <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
              </a>
            </div>
            <!-- /Logo -->

            <!-- Mobile toggle -->
            <button class="navbar-toggle">
              <span></span>
            </button>
            <!-- /Mobile toggle -->
          </div>



          <!-- Navigation -->
          <nav id="nav">
            <ul class="main-menu nav navbar-nav navbar-right">
              <li><a style="color:black;"href="{% url 'accounts:view_profile' %}">Dashboard</a></li>
              <!-- <li><a href="/accounts/profile/edit">Edit Profile</a></li> -->
              <li><a style="color:black;" href="{% url 'accounts:edit_details' %}">Siwes Info</a></li>
              <li><a style="color:black;" href="{% url 'password_reset' %}">Change Password</a></li>
              <li><a style="color:black;" href="{% url 'logout' %}">Log out</a></li>
            </ul>
          </nav>
          <!-- /Navigation -->

      </header>
      <!-- /Header -->


        <div class="bg-img"  style="color:black;">
          <form style="position: absolute;right:0;opacity:1;min-width:490px; margin: 20px;padding: 16px;background-color:white;"method="POST">
            {% csrf_token %}

            <div class="row">
              <div class="col-md-12">
                  <p>{{ form|crispy }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-8">

              </div>
              <div class="col-md-4">
                <input type="submit" name="" value="Submit" class="btn btn-success">
              </div>
            </div>
          </form>
        </div>
        <br><br>


        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <p style="color:black;"><strong> © 2021. Ogbe Larry Inc | FUPRE SIWES C.S </strong> </p>
            </div>
          </div>
          </div>



          <!-- preloader -->
          <div id='preloader'><div class='preloader'></div></div>
          <!-- /preloader -->

          <!-- jQuery Plugins -->
          <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
          <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
          <script type="text/javascript" src="{% static "js/main.js" %}"></script>
  </body>
</html>

templates/accounts/reset_complete.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>Resetcomplete</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
  </head>
  <body>

    <br>

    <!-- Header -->
    <header id="header" class="">
      <div class="container">

        <div class="navbar-header">
          <!-- Logo -->
          <div class="navbar-brand">
            <a class="logo" href="{% url 'home' %}">
              <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
            </a>
          </div>
          <!-- /Logo -->

          <!-- Mobile toggle -->
          <button class="navbar-toggle">
            <span></span>
          </button>
          <!-- /Mobile toggle -->
        </div>

        <!-- Navigation -->
        <!-- <nav id="nav">
          <ul class="main-menu nav navbar-nav navbar-right">
            <li><a style="color:black;"href="{% url 'accounts:view_profile' %}">Dashboard</a></li>
            <li><a href="/accounts/profile/edit">Edit Profile</a></li>
            <li><a style="color:black;" href="{% url 'accounts:edit_details' %}">Siwes Info</a></li>
            <li><a style="color:black;" href="{% url 'accounts:payments' %}">Payments</a></li>
            <li><a style="color:black;" href="{% url 'accounts:change_password' %}">Change Password</a></li>
            <li><a style="color:black;" href="{% url 'accounts:user_logout' %}">Log out</a></li>
          </ul>
        </nav> -->
        <!-- /Navigation -->
      </div>

    </header>
    <!-- /Header -->


        <br><br><br>
        <br><br><br>

          <div class="container">
            <div class="row">
            <h2 style="color:#C00;vertical-align:middle;text-align:center"> Password Reset Successfully. </h2>
          </div>
        </div>
        <br>

        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <ol>
                    <li> <h4 style="color:black;">   You've successfully changed your passsword.
                                                     <br>
                                                     <p></p>
                                                      Click the button below to proceed</h4></li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="container">
          <a style="color:black;" class="btn btn-success" href="{% url 'login' %}">Login Here</a>
        </div>


        <br><br><br>
        <br><br><br>
        <br><br><br>

        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <p style="color:black;"><strong> © 2021. Ogbe Larry Inc | FUPRE SIWES C.S </strong> </p>
            </div>
          </div>
          </div>


        <!-- preloader -->
        <div id='preloader'><div class='preloader'></div></div>
        <!-- /preloader -->




        <!-- jQuery Plugins -->
        <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/main.js" %}"></script>
  </body>
</html>

templates/accounts/reset_confirm.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>Confirm</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
  </head>
  <body>

      <br>

      <!-- Header -->
      <header id="header" class="">
        <div class="container">

          <div class="navbar-header">
            <!-- Logo -->
            <div class="navbar-brand">
              <a class="logo" href="{% url 'home' %}">
                <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
              </a>
            </div>
            <!-- /Logo -->

            <!-- Mobile toggle -->
            <button class="navbar-toggle">
              <span></span>
            </button>
            <!-- /Mobile toggle -->
          </div>


          <!-- Navigation -->
          <!-- <nav id="nav">
            <ul class="main-menu nav navbar-nav navbar-right">
              <li><a style="color:black;"href="{% url 'accounts:view_profile' %}">Dashboard</a></li>
              <li><a href="/accounts/profile/edit">Edit Profile</a></li>
              <li><a style="color:black;" href="{% url 'accounts:edit_details' %}">Siwes Info</a></li>
              <li><a style="color:black;" href="{% url 'accounts:payments' %}">Payments</a></li>
              <li><a style="color:black;" href="{% url 'accounts:change_password' %}">Change Password</a></li>
              <li><a style="color:black;" href="{% url 'accounts:user_logout' %}">Log out</a></li>
            </ul>
          </nav> -->
          <!-- /Navigation -->

      </div>
      </header>
      <!-- /Header -->

        <br><br><br>


        <div class="container" style="color:black;">
          <h1 style="color:#C00;">Enter New Password</h1>
          <br><br>
          <form class=""  method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="form-group col-md-4 mb-0">
              </div>
              <div class="form-group col-md-4 mb-0">
                  <p>{{ form|crispy }}</p>
              </div>
              <div class="form-group col-md-4 mb-0">

              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-7 mb-0">

              </div>
            <div class=" col-md-5">
              <input type="submit" name="" value="submit" class="btn btn-success">
            </div>
            <div class="form-group col-md-0 mb-0">

            </div>
          </div>
        </form>
      </div>
      <br><br>

      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <p style="color:black;"><strong> © 2021. Ogbe Larry Inc | FUPRE SIWES C.S </strong> </p>
          </div>
        </div>
        </div>




        <!-- preloader -->
        <div id='preloader'><div class='preloader'></div></div>
        <!-- /preloader -->

        <!-- jQuery Plugins -->
        <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/main.js" %}"></script>
  </body>
</html>

templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:"  %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your matriculation number, in case you've forgotten:" %} {{user.get_username}}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% trans "© 2019. Onose_Anthonii Inc | PaperCode C.S" %}
{% endautoescape %}