accounts/urls.py
from django.urls import path
from accounts import views
#from django.contrib.auth.views import (password_reset, password_reset_done,
 #      
 #                                  password_reset_confirm, password_reset_complete)




#Template Tagging
app_name = 'accounts'

urlpatterns = [

    # path('login/', views.user_login,  name='user_login'),
    # path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.StudentSignUpView.as_view(), name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/siwes/', views.edit_details, name='edit_details'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    # path('change-password/', views.change_password, name='change_password'),

    #path('reset-password/', password_reset,{'template_name':
    #'accounts/reset_password.html', 'post_reset_redirect':
    #'accounts:password_reset_done', 'email_template_name':
    #'accounts/reset_password_email.html'}, name='reset_password'),


    #path('reset_password-password/done/',  password_reset_done, {'template_name':
    #'accounts/reset_done.html'}, name='password_reset_done'),

    #path('reset_password-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',  password_reset_confirm, {'template_name':
    #'accounts/reset_confirm.html', 'post_reset_redirect':
    #'accounts:password_reset_complete'}, name='password_reset_confirm'),


    #path('reset-password/complete/',  password_reset_complete, {'template_name':
    #'accounts/reset_complete.html'}, name='password_reset_complete'),

]

fupreproject/urls.py
from django.contrib import admin
from django.urls import include, path
from accounts import views
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('contact/', views.ContactPage, name='contact'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

            # Autenticate 3rd party
    path('profile/login/', auth_views.LoginView.as_view(), name='login'),
    path('profile/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('profile/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>About</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
  </head>
  <body>

          <br><br>

          <!-- Header -->
          <header id="header" class="">
            <div class="container">

              <div class="navbar-header">
                <!-- Logo -->
                <div class="navbar-brand">
                  <a class="logo" href="{% url 'home' %}">
                    <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
                  </a>
                </div>
                <!-- /Logo -->

                <!-- Mobile toggle -->
                <button class="navbar-toggle">
                  <span></span>
                </button>
                <!-- /Mobile toggle -->
              </div>

              <!-- Navigation -->
              <nav id="nav">
                {% if user.is_authenticated %}
                <ul class="main-menu nav navbar-nav navbar-right">
                  <li><a style="color:black;"href="{% url 'accounts:view_profile' %}">Dashboard</a></li>
                  <!-- <li><a href="/accounts/profile/edit">Edit Profile</a></li> -->
                  <li><a style="color:black;" href="{% url 'accounts:edit_details' %}">Siwes Info</a></li>
                  <li><a style="color:black;" href="{% url 'accounts:change_password' %}">Change Password</a></li>
                  <li><a style="color:black;" href="{% url 'accounts:user_logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="main-menu nav navbar-nav navbar-right">
                  <li><a style="color:black;" href="{% url 'home' %}">Home</a></li>
                  <li><a style="color:black;" href="{% url 'about' %}">About</a></li>
                  <li><a style="color:black;" href="{% url 'contact' %}">Contact</a></li>
                  <li><a style="color:black;" href="{% url 'login' %}">Login</a></li>
                  <li><a style="color:black;" href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif%}
              </nav>
              <!-- /Navigation -->

            </div>
          </header>
          <!-- /Header -->
          <br><br><br>
          <div class="container">
            <!-- row -->
            <div class="row">

              <div class="col-md-4">
                  <img style="border-radius:50%;"src="{% static 'images/director.jpg' %}" alt="">
                  <p></p>
                  <p style="color:black;" class="lead">Dr. Enaibe Aroghene Edison</p>
              </div>

              <div class="col-md-8">
                <h3 style="color:#C00;">Director of Siwes Unit</h3>
                <p style="color:black;" class="lead">  Dr. Enaibe Aroghene Edison is an Associate Professor of Theoretical Physics in the College of Science, Department of Physics. Born on April 26 1970, in Benin City, Edo State, Dr. Enaibe obtained his Doctor of Philosophy degree (Ph.D) in Theoretical Physics from the University of Benin, in 2003 specializing in Condensed Matter Physics. He also holds a Bachelor’s Degree and a Master’s degree in Theoretical Physics from the University of Benin, (UNIBEN) in 1992 and 1998 respectively.
                </p>
              </div>



            </div>
            <!-- /row -->

          </div>

                          <!-- About Siwes -->
                      <div id="courses" class="section">

                        <!-- container -->
                        <div class="container">

                          <!-- row -->
                          <div class="row">
                            <div class="section-header text-center">
                              <h2 style="color:#C00;">Student Industrial Work Experience Scheme {SIWES} </h2>
                            </div>
                          </div>
                          <!-- /row -->
                        </div>
                        <!-- container -->

                        <div class="container">
                        <div class="row">
                          <div class="col-md-12">
                            <div class="panel panel-default">
                              <div class="panel-body">
                                <p style="color:black;" class="lead">The Students’ Industrial Work Experience Scheme (SIWES) is a six-credit course that is established
                                  for students to gain practical experience of the application of theoretical course work they study in the university.
                                  The SIWES is done for a period of six months and it's undertaken at 300 Level second semester for Science students
                                  and 400 Level second semester for students in the College of Technology.
                                  At the end of the program, the Federal Government gives some allowances to the students to cover minor expenses they incurred during the training.
                                  In order to achieve the aim of the SIWES Program, the SIWES Unit was established in every institution and made mandatory by the Federal Government of Nigeria
                                  and it is regulated by the Industrial Training Fund (ITF) in order to achieve the objectives of the SIWES.
                                </p>
                                <p></p>
                                <p style="color:black;" class="lead">The Students’ Industrial Work Experience Scheme (SIWES) Unit of FUPRE was inaugurated on the 15th of February, 2010 with the responsibility to;</p><br>

                                <ul style="color:black;" class="lead">

                                  <li>** Prepare and submit eight copies of Master Listsand eight copies of placement lists of each SIWES year to the ITF. All submissions must be made through the National Universities Commission (NUC). However two advanced copies should be sent to the ITF Warri Area Office.</li><br>

                                  <li>** Apply job-specifications as prepared for all the accredited courses and award appropriate credit units in accordance with Federal Government minimum academic standard guidelines.</li><br>

                                  <li>** Identify placement opportunities for students’ attachment with employers.</li><br>

                                  <li>** Supervise students at their places of attachment and sign their log-books.</li><br>

                                  <li>** Organize orientation courses in collaboration with the Industrial Training Fund (ITF) for the students.</li><br>

                                  <li>** Submit comprehensive reports of the scheme to Industrial Training Fund ITF through Nigerian Universities Commission NUC. The ITF Form 8 at the end of every year’s programme is submitted to ITF.</li><br>

                                  <li>** Ensure payment of outstanding allowances and render all returns to the ITF during the SIWES year.</li><br>

                                  <li>** Submit all completed ITF form 8 to the nearest ITF Area Office.</li><br>

                                </ul>

                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
                      <!-- /About Siwes -->
                  </div>

                  <div class="container">
                    <div class="row">
                      <div class="col-md-4">
                        <p style="color:black;"><strong> © 2019. Onose_Anthonii Inc | PaperCode C.S </strong> </p>
                      </div>
                    </div>
                  </div>



          <!-- preloader -->
          <div id='preloader'><div class='preloader'></div></div>
          <!-- /preloader -->

          <!-- jQuery Plugins -->
          <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
          <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
          <script type="text/javascript" src="{% static "js/main.js" %}"></script>

  </body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

                <title>{% block title %}SIWES PORTAL {% endblock %}</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
    <style>
          .accordion {
            background-color:  #003679;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
          }

          .active, .accordion:hover {
            background-color: #C00;
          }

          .accordion:after {
            content: '\002B';
            color: #777;
            font-weight: bold;
            float: right;
            margin-left: 5px;
          }

          .active:after {
            content: "\2212";
          }

          .panel {
            padding: 0 18px;
            background-color: white;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
          }
    </style>
  </head>
  <body>

      <br><br>

      <!-- Header -->
      <header id="header" class="">
        <div class="container">

          <div class="navbar-header">
            <!-- Logo -->
            <div class="navbar-brand">
              <a class="logo" href="{% url 'home' %}">
                <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
              </a>
            </div>
            <!-- /Logo -->

            <!-- Mobile toggle -->
            <button class="navbar-toggle">
              <span></span>
            </button>
            <!-- /Mobile toggle -->
          </div>

          <!-- Navigation -->
          <nav id="nav">
            <ul class="main-menu nav navbar-nav navbar-right">
              <li><a style="color:black;" href="{% url 'home' %}">Home</a></li>
              <li><a style="color:black;" href="{% url 'about' %}">About</a></li>
              <li><a style="color:black;" href="{% url 'contact' %}">Contact</a></li>
              <li><a style="color:black;" href="{% url 'login' %}">Login</a></li>
              <li><a style="color:black;" href="{% url 'accounts:register' %}">Register</a></li>
            </ul>
          </nav>
          <!-- /Navigation -->

        </div>
      </header>




      <br><br>


      {% block content %}

      {% endblock content %}

        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <p style="color:black;"><strong> © 2021. Ogbe Larry Inc | FUPRE SIWES C.S </strong> </p>
            </div>
          </div>
          </div>





      <!-- preloader -->
      <div id='preloader'><div class='preloader'></div></div>
      <!-- /preloader -->


      <!-- Custom Jquery -->
      <script>
      var acc = document.getElementsByClassName("accordion");
      var i;

      for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
          this.classList.toggle("active");
          var panel = this.nextElementSibling;
          if (panel.style.maxHeight){
            panel.style.maxHeight = null;
          } else {
            panel.style.maxHeight = panel.scrollHeight + "px";
          }
        });
      }
      </script>
      <!-- /Custom Jquery -->


      <!-- jQuery Plugins -->
      <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
      <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
      <script type="text/javascript" src="{% static "js/main.js" %}"></script>

  </body>
</html>

templates/contact.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static%}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>Contact</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
  </head>
  <body>

          <br><br>

          <!-- Header -->
          <header id="header" class="">
            <div class="container">

              <div class="navbar-header">
                <!-- Logo -->
                <div class="navbar-brand">
                  <a class="logo" href="{% url 'home' %}">
                    <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
                  </a>
                </div>
                <!-- /Logo -->

                <!-- Mobile toggle -->
                <button class="navbar-toggle">
                  <span></span>
                </button>
                <!-- /Mobile toggle -->
              </div>

              <!-- Navigation -->
              <nav id="nav">
                {% if user.is_authenticated %}
                <ul class="main-menu nav navbar-nav navbar-right">
                  <li><a style="color:black;"href="{% url 'accounts:view_profile' %}">Dashboard</a></li>
                  <!-- <li><a href="/accounts/profile/edit">Edit Profile</a></li> -->
                  <li><a style="color:black;" href="{% url 'accounts:edit_details' %}">Siwes Info</a></li>
                  <li><a style="color:black;" href="{% url 'change_password' %}">Change Password</a></li>
                  <li><a style="color:black;" href="{% url 'logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="main-menu nav navbar-nav navbar-right">
                  <li><a style="color:black;" href="{% url 'home' %}">Home</a></li>
                  <li><a style="color:black;" href="{% url 'about' %}">About</a></li>
                  <li><a style="color:black;" href="{% url 'contact' %}">Contact</a></li>
                  <li><a style="color:black;" href="{% url 'login' %}Login</a></li>
                  <li><a style="color:black;" href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif%}
              </nav>
              <!-- /Navigation -->

            </div>
          </header>
          <!-- /Header -->

      <br><br><br><br>
      <div class="container">

        <!-- The map -->
        <div class="row map-wrap" style="width:100%; height: 445px;" id="map">
          <iframe style="border:0; width:100%; height: 445px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3971.3161047076264!2d5.8584725144476275!3d5.520023335546032!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1041b03234470647%3A0x28800e52638171d1!2sFederal+University+of+Petroleum+Resources+Effurun!5e0!3m2!1sen!2sng!4v1558959476269!5m2!1sen!2sng" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div><br><br><br><br><br>


      <!-- contact information -->
      <div class="col-md-7 ">
        <h4 style="color:#C00;">Contact Information</h4>
        <ul style="color:black;" class="contact-details">
          <li><i class="lnr lnr-envelope">Pc</i>siwes@fupre.edu.ng</li>
          <li><i class="fa fa-phone">Pc</i>+234 903 500 0122</li>
          <li><i class="fa fa-map-marker">Pc</i>Federal University of Petroleum Resources, P.M.B 1221, Effurun, Delta State, Nigeria</li>
        </ul>
      </div>
      <!-- contact information -->

        <!-- contact form -->
      <div class="col-md-5">
        <div class="contact-form">
          <h4 style="color:#C00;">Send A Message</h4>
          <form  method="POST">
            {% csrf_token %}
            <input class="input"  type="email" name="email" placeholder="Email">
            <input class="input" type="text" name="subject" placeholder="Subject">
            <textarea class="input" name="message" placeholder="Enter your Message"></textarea>
            <button class="main-button icon-button pull-right">Send Message</button><br><br><br>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br><br>
    <!-- /contact form -->


    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <p style="color:black;"><strong> © 2021. Ogbe Larry Inc | FUPRE SIWES C.S </strong> </p>
        </div>
      </div>
      </div>




    <!-- preloader -->
    <div id='preloader'><div class='preloader'></div></div>
    <!-- /preloader -->

    <!-- jQuery Plugins -->
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/main.js" %}"></script>

  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Fupre, Siwes, Portal">
    <meta name="author" content="PaperCode C.S">
    <meta name="description" content="This is a site to enable eligible students of the Federal University of Petroleum Resources Effurun
                register for the student industrial work experience scheme (SIWES)">

    <title>Index</title>

    <!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet"  href="{% static 'css/style.css' %}"/>
    <style>
          .accordion {
            background-color:  #003679;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
          }

          .active, .accordion:hover {
            background-color: #C00;
          }

          .accordion:after {
            content: '\002B';
            color: #777;
            font-weight: bold;
            float: right;
            margin-left: 5px;
          }

          .active:after {
            content: "\2212";
          }

          .panel {
            padding: 0 18px;
            background-color: white;
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
          }
    </style>
  </head>
  <body>

      <br><br>

      <!-- Header -->
      <header id="header" class="">
        <div class="container">

          <div class="navbar-header">
            <!-- Logo -->
            <div class="navbar-brand">
              <a class="logo" href="{% url 'home' %}">
                <img src="{% static "images/banner.png" %}" alt="Uh. Oh! Resource not found">
              </a>
            </div>
            <!-- /Logo -->

            <!-- Mobile toggle -->
            <button class="navbar-toggle">
              <span></span>
            </button>
            <!-- /Mobile toggle -->
          </div>

          <!-- Navigation -->
          <nav id="nav">
            <ul class="main-menu nav navbar-nav navbar-right">
              <li><a style="color:black;" href="{% url 'home' %}">Home</a></li>
              <li><a style="color:black;" href="{% url 'about' %}">About</a></li>
              <li><a style="color:black;" href="{% url 'contact' %}">Contact</a></li>
              <li><a style="color:black;" href="{% url 'login' %}">Login</a></li>
              <li><a style="color:black;" href="{% url 'accounts:register' %}">Register</a></li>
            </ul>
          </nav>
          <!-- /Navigation -->

        </div>
      </header>
      <!-- /Header -->

            <!-- Home -->
      <div id="home" class="hero-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style='background-image: url("{% static "images/hb.png" %}")'>

        </div>
        <!-- /Backgound Image -->

        <div class="home-wrapper">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
                <h1 class="white-text">Federal University Of Petroleum Resources</h1>
                <p class="lead white-text">Siwes Online Portal.</p>
                <a class="main-button icon-button" href="{% url 'accounts:register' %}">Get Started!</a>
              </div>
            </div>
          </div>
        </div>

      </div>
      <!-- /Home -->

      <!-- About Portal-->
		<div id="about" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<div class="col-md-6">
						<div class="section-header">
							<h2 style="color:#C00;">Welcome to the University Siwes Portal</h2>
							<p  style="color:black;" class="lead">Fastracking siwes procedures.</p>
						</div>

						<!-- feature -->
						<div class="feature">
							<i class="feature-icon fa fa-flask"></i>
							<div class="feature-content">
								<h4 style="color:#C00;">Online Registration </h4>
								<p style="color:black;">Fastracking your registration for the student industrial work experience scheme.</p>
							</div>
						</div>
						<!-- /feature -->

					

					

					</div>

          <div class="col-md-1">
          </div>

					<div class="col-md-5">
						<div class="about-img">
							<img style="height:350px;width:480px" src="{% static 'images/ab.jpg' %}" alt="">
						</div>
					</div>

				</div>
				<!-- row -->

			</div>
			<!-- container -->
		</div>
		<!-- /About Portal-->


        <button style="color:white;"class="accordion">APPLICATION FOR THE 2020/2021 SESSION SIWES PROGRAMME NOW OPEN</button>
        <div class="panel">
          <p class="lead panel-heading" style="color:black;">
            Posted by: Admin,
            <span>Date: August 29, 2021, 14:13 p.m. </span>
          </p>
          <p class=""style="color:black;">This is to notify all eligible stakeholders that the University siwes portal is now open
                    for registration for the 2019/2020 session of the student industrial work experience scheme . </p>
        </div>
        <button style="color:white;"class="accordion">SIWES ORIENTATION PROGRAMME FOR 2020/2021 SESSION</button>
        <div class="panel">
          <p class="lead panel-heading" style="color:black;">
            Posted by: Admin,
            <span>Date: May 7, 2021, 10:43 a.m. </span>
          </p>
          <p class=""style="color:black;">This is to notify all eligible stakeholders that the orientation programme for
                  the 2019/2020 session is to hold on Wednesday 15th May 2021 by 10am at Lecture Theatre 1. All stakeholders
                    are advised to attend.</p>
        </div>
      </div>
      <br><br>




        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <p style="color:black;"><strong> © 2021. Ogbe Larry Inc | FUPRE SIWES C.S </strong> </p>
            </div>
          </div>
          </div>





      <!-- preloader -->
      <div id='preloader'><div class='preloader'></div></div>
      <!-- /preloader -->


      <!-- Custom Jquery -->
      <script>
      var acc = document.getElementsByClassName("accordion");
      var i;

      for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
          this.classList.toggle("active");
          var panel = this.nextElementSibling;
          if (panel.style.maxHeight){
            panel.style.maxHeight = null;
          } else {
            panel.style.maxHeight = panel.scrollHeight + "px";
          }
        });
      }
      </script>
      <!-- /Custom Jquery -->


      <!-- jQuery Plugins -->
      <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
      <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
      <script type="text/javascript" src="{% static "js/main.js" %}"></script>

  </body>
</html>

templates/message_display.html
{% if messages %}

A simple primary alert—check it out!

<div class="alert alert-primary alert-dismissible" role="alert">
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}" style="list-style: none; font-size: 15px;">
                    {% if 'html_safe' in message.tags %}{{ message|safe }}{% else %}{{ message}}{% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
{% endif %}